#!/bin/bash
apt-get update
apt install -y apache2
apt-get install mysql-server -y
apt-get install apache2 -y
apt-get install php-mysql -y
apt install php libapache2-mod-php -y
rm /var/www/html/index.html
systemctl restart apache2
